version: '3.8'

# 데이터베이스 컨테이너를 설정합니다.
services:
  db:
    image: mysql:8.0
    container_name: school_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: koposuer
      MYSQL_DATABASE: kopodb
      MYSQL_USER: kopouser        
      MYSQL_PASSWORD: koposuer
    ports:
      - "3308:3306" # "feat: docker-compose.yml 수정" : 호스트의 3308 포트를 컨테이너의 3306 포트로 매핑
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  # 백엔드 컨테이너를 설정합니다.
  backend:
      build: ./backend
      container_name: school_backend
      restart: always
      ports:
        - "3000:3000"
      environment:
        DB_HOST: db
        DB_USER: kopouser
        DB_PASSWORD: koposuer
        DB_NAME: kopodb
      depends_on:
        - db
  # "feat: docker-compose.yml 수정" : backend를 service 하위에 들어가도록 tab.

volumes:
  mysql_data: