version: '3.8'

# 데이터베이스 컨테이너를 설정합니다.
services:
  db:
    image: mysql:8.0
    container_name: school_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: koposuer
      MYSQL_DATABASE: kopodb
      MYSQL_USER: kopouser        
      MYSQL_PASSWORD: koposuer
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

# 백엔드 컨테이너를 설정합니다.
backend:
    build: ./backend
    container_name: school_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: kopouser
      DB_PASSWORD: koposuer
      DB_NAME: kopodb
    depends_on:
      - db

volumes:
  mysql_data: